package(default_visibility = ["//visibility:public"])

java_library(
    name = "slice",
    srcs = [
        "Slice.java",
        "ByteBufferSlice.java",
        "BytewiseSliceComparator.java",
    ],
    deps = [
    ]
)