package(default_visibility = ["//visibility:public"])

java_library(
    name = "sstable",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//main/org/ricebin/slice",
        "@maven//:com_google_guava_guava",
    ]
)
